run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - misspell

linters-settings:
  govet:
    disable:
      - fieldalignment
      - shadow
  revive:
    rules:
      - name: exported
        disabled: true
      - name: unexported-return
        disabled: false
      - name: time-naming
        disabled: false

issues:
  exclude-dirs:
    - example-src
    - dist
    - package
