run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofumpt
    - revive
    - misspell
    - gocritic

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: exported
        disabled: true
      - name: unexported-return
        disabled: false
      - name: time-naming
        disabled: false
  gocritic:
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - unnamedResult
      - paramTypeCombine
      - uncheckedInlineErr
      - dupSubExpr
      - dupImport
      - nestingReduce
      - emptyStringTest
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-dirs:
    - example-src
    - dist
    - package
